SELECT  E.nNroEquipo
       ,E.Nombre
       ,TMT.TRACCION
	   ,TMPH.PROPULSIONHIDRAULICA
	   ,E.TM_OTRAS
	   ,CMU.UBICACION
	   ,E.CM_OTRAS
	   ,MM.MARCA
	   ,E.M_VELOCIDAD
	   ,E.M_POTENCIAHP
	   ,E.M_NROIDENTIFICADORES
	   ,TTT.TENSIONTIPO
	   ,E.T_ALTERNACONTROLADA
	   ,E.T_FRECVARIABLE
	   ,E.R_NROPISOS
	   ,E.R_PARADAS
	   ,E.R_ACCESOS
	   ,E.R_ACCESOSOPYAD
	   ,E.V_UNICA
	   ,E.V_ALTABAJA
	   ,TP.TIPOPARACAIDAS
	   ,E.TPCAB_OTRO
	   ,TPCP.TIPOPARACAIDAS as TipoParacaidasContrapeso
	   ,E.TPCONTR_OTRO
	   ,TPP.TIPOPARAGOLPE
	   ,E.P_OTRO
	   ,TMTi.TIPOMANIOBRA
	   ,E.TMAN_OTRA
	   ,SA.SELECTIVAACUMULATIVA 
	   ,TC.TIPOCONTROL
	   ,E.CT_PERSONAS
	   ,E.CT_KG
	   ,E.PC_MATERIAL
	   ,CASE E.PC_MANUAL 
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PCManual
	   ,PCMT.TIPOPUERTAMANUAL
	   ,E.PC_MANUALOTRA
	   ,CASE E.PC_AUTOMATICA 
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PCAutoMatica
	   ,PAT.PUERTAAUTOMATICATIPO
	   ,PAC.PUERTAAUTOMATICACORRIENTE
	   ,E.PC_AUTOMATICAOTRA
	   ,E.PR_MATERIAL
	   ,CASE E.PR_MANUAL
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PRManual
		,PRMT.TIPOPUERTAMANUAL
		,PR_MANUALOTRA
	   ,CASE E.PR_AUTOMATICA
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PRAutomatica
		,PATA.PUERTAAUTOMATICAARRASTRE
		,CASE E.PH_PISTONCENTRAL
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PHPISTONCENTRAL
		,CASE E.PH_PISTONLATERAL
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PHPISTONLATERAL
		,CASE E.PH_PISTONENTERRADO
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PHPISTONENTERRADO
		,CASE E.PH_PISTONTELESCOPICO
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PHPISTONTELESCOPICO
		,CASE PH_RELACION2_1
	      WHEN 1 THEN 'SI'
		  WHEN 0 THEN 'NO'
		END as PHRELACION2_1
		,TXOBSERVACIONES
FROM tbEquipos E
      LEFT JOIN TUGTIPOSMAQUINASTRACCION TMT ON TMT.IDTIPOMAQTRACCION = E.TM_TRACCION
	  LEFT JOIN TUGTIPOSMAQPROPHIDRAULICA TMPH ON TMPH.IDTIPOMAQPROPHIDRAULICA = E.TM_PROPHIDRAULICA
	  LEFT JOIN TUGCUARTOMAQUBICACION CMU ON CMU.IDCUARTOMAQUBICACION = E.CM_UBICACION
	  LEFT JOIN TUGMOTORESMARCAS MM ON MM.IDMOTORMARCA = E.M_MARCA
	  LEFT JOIN TUGTENSIONESTIPO TTT ON TTT.IDTENSIONTIPO = E.T_TIPO
	  LEFT JOIN TUGTIPOSPARACAIDAS TP ON TP.IDTIPOPARACAIDAS = E.TPCAB_TIPO
	  LEFT JOIN TUGTIPOSPARACAIDAS TPCP ON TPCP.IDTIPOPARACAIDAS = E.TPCONTR_TIPO
	  LEFT JOIN TUGTIPOSPARAGOLPES TPP ON TPP.IDTIPOPARAGOLPE = E.P_TIPO
	  LEFT JOIN TUGTIPOSMANIOBRASTIPOS TMTi ON TMTi.IDTIPOMANIOBRATIPO = E.TMAN_TIPO
	  LEFT JOIN TUGSELECTIVAACUMULATIVATIPOS SA ON SA.IDSELECTIVAACUMULATIVATIPO = E.SA_TIPO
	  LEFT JOIN TUGTIPOSCONTROLTIPOS TC ON TC.IDTIPOCONTROLTIPO = E.TC_TIPO
	  LEFT JOIN TUGPUERTASMANUALESTIPOS PCMT ON PCMT.IDPUERTAMANUALTIPO = E.PC_MANUALTIPO
	  LEFT JOIN TUGPUERTASAUTOMATICASTIPOS PAT ON PAT.IDPUERTAAUTOMATICATIPO = E.PC_AUTOMATICATIPO
	  LEFT JOIN TUGPUERTASAUTOMATICASCORRIENTE PAC ON PAC.IDPUERTAAUTOMATICACORRIENTE = E.PC_AUTOMATICACORRIENTE
	  LEFT JOIN TUGPUERTASMANUALESTIPOS PRMT ON PRMT.IDPUERTAMANUALTIPO = E.PR_MANUALTIPO
	  LEFT JOIN TUGPUERTASAUTOMATICASARRASTRE PATA ON PATA.IDPUERTAAUTOMATICAARRASTRE = E.PR_AUTOMATICATIPOARRASTRE
WHERE (E.BVISIBLE = 1) AND (E.IDEQUIPO = :idEquipo)
