ALTER TABLE tbEquipos ALTER M_VELOCIDAD TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER M_POTENCIAHP TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER R_ACCESOSOPYAD TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER V_UNICA TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER V_ALTABAJA TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER PC_MATERIAL TYPE VARCHAR(200);
ALTER TABLE tbEquipos ALTER PR_MATERIAL TYPE VARCHAR(200);
ALTER TABLE tbEquipos ADD txObservaciones VARCHAR (3500);
